# Global Setting
spring.application.name=five-rock-run
spring.profiles.active=local

# JPA Global Setting
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## DB Setting
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/fiveRockRun
spring.datasource.username=root
spring.datasource.password=trinket99
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Redis Setting
spring.data.redis.host=localhost
spring.data.redis.port=26379

## JWT
jwt.secret.key=bVk4JUpmJiFtWnAycndBKmVMeFd2I3VESFFATjFzRzN0SHlCOXpDMF5LWGY0ViVv